[tool.ruff]
select = [
  "E",   # pycodestyle (Error)
  "W",   # pycodestyle (Warning)
  "N",   # pep8-naming
  "I",   # isort
  "A",   # flake8-builtins
  "B",   # flake8-bugbear
  "ANN", # flake8-annotations
  "RUF", # Ruf-specific rules
]
line-length = 79
